Repository UMC-1-Footprint/Footprint-iOS, pull requests merged in 2022-09, with the labels that each got.

#16 [Feat/#13] 로그인 및 약관동의 UI 구현
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/checkbox_off.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/checkbox_off.imageset/checkbox_off.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/checkbox_on.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/checkbox_on.imageset/checkbox_on.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/footBigLogo.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/footBigLogo.imageset/footBigLogo.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/footBigLogo.imageset/footBigLogo@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/footBigLogo.imageset/footBigLogo@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/footprintBigLogo.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/footprintBigLogo.imageset/footprintBigLogo.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/googleIcon.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/googleIcon.imageset/googleIcon.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/kakaoIcon.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/kakaoIcon.imageset/kakaoIconsvg.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/moreIcon.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/moreIcon.imageset/moreIcon.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/moreIcon.imageset/moreIcon@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/moreIcon.imageset/moreIcon@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/notePencil.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/notePencil.imageset/notePencil.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/road.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/agreementView/road.imageset/road.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/badgeBackground.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/badgeBackground.imageset/badgeBackground.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/badgeBackground.imageset/badgeBackground@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/badgeBackground.imageset/badgeBackground@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/emptyBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/emptyBadge.imageset/emptyBadge.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/emptyBadge.imageset/emptyBadge@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/emptyBadge.imageset/emptyBadge@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/proBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/proBadge.imageset/proBadge.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/proBadge.imageset/proBadge@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/proBadge.imageset/proBadge@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadge.imageset/representBadgeImage.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadge.imageset/representBadgeImage@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadge.imageset/representBadgeImage@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadgeBackground.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadgeBackground.imageset/representBadgeBackground.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadgeBackground.imageset/representBadgeBackground@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/representBadgeBackground.imageset/representBadgeBackground@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/startBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/startBadge.imageset/startBadge.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/startBadge.imageset/startBadge@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeView/startBadge.imageset/startBadge@3x.png
  FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
  FootprintIOS/FootprintIOS/Sources/View/Reusable/FootprintButton.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Login/AgreementReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Login/AgreementViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Login/LoginViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
Labels: 🐿 소진, Style

#21 [Feat#18] 설정 - 공지사항 UI
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/icon logo.imageset/Contents.json
  FootprintIOS/FootprintIOS/Sources/Base/BaseTableViewCell.swift
  FootprintIOS/FootprintIOS/Sources/Extension/Rx+Ext.swift
  FootprintIOS/FootprintIOS/Sources/View/MyPage/Notice/Cell/NoticeTableViewCell.swift
  FootprintIOS/FootprintIOS/Sources/View/MyPage/Notice/Cell/NoticeTableViewCellReactor.swift
  FootprintIOS/FootprintIOS/Sources/View/MyPage/Notice/NoticeSectionModel.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Notice/NoticeReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Notice/NoticeViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Setting/SettingViewController.swift
  Project.swift
  Tuist/Dependencies.swift
Labels: 🐣 영모

#22 [Feat/#19] 네트워크 레이어 구축
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIEnvironment.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIError.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/BaseModel.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/EndPoint.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/HTTPMethod.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/NetworkRequest.swift
  FootprintIOS/FootprintIOS/Sources/Network/Test/TestAPIManager.swift
  FootprintIOS/FootprintIOS/Sources/Network/Test/TestEndPoint.swift
  FootprintIOS/FootprintIOS/Sources/Network/Test/TestManager.swift
  FootprintIOS/FootprintIOS/Sources/Network/Test/TestModel.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Test/TestVC.swift
Labels: 🐿 소진
