Repository UMC-1-Footprint/Footprint-iOS, pull requests merged in 2022-08, with the labels that each got.

#6 Feature/#5
  FootprintIOS/FootprintIOS/Resources/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Assets.xcassets/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Colors.xcassets/BlueM.colorset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Colors.xcassets/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/backButtonIcon.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/backButtonIcon.imageset/backButtonIcon.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/backButtonIcon.imageset/backButtonIcon@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/backButtonIcon.imageset/backButtonIcon@3x.png
  FootprintIOS/FootprintIOS/Resources/LaunchScreen.storyboard
  FootprintIOS/FootprintIOS/Sources/AppDelegate.swift
  FootprintIOS/FootprintIOS/Sources/Base/BaseCollectionReusableView.swift
  FootprintIOS/FootprintIOS/Sources/Base/BaseCollectionViewCell.swift
  FootprintIOS/FootprintIOS/Sources/Base/BaseTableViewCell.swift
  FootprintIOS/FootprintIOS/Sources/Base/BaseView.swift
  FootprintIOS/FootprintIOS/Sources/Base/BaseViewController.swift
  FootprintIOS/FootprintIOS/Sources/Base/NavigationBarViewController.swift
  FootprintIOS/FootprintIOS/Sources/Extension/UIColor+Ext.swift
  FootprintIOS/FootprintIOS/Sources/Extension/UIImage+Ext.swift
  FootprintIOS/FootprintIOS/Sources/Extension/UIView+Ext.swift
  FootprintIOS/FootprintIOS/Sources/SceneDelegate.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Calendar/CalendarViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Footprint/FootprintViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Recommend/RecommendViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/TabBar/TabBarController.swift
  FootprintIOS/FootprintIOS/Tests/AppTests.swift
  FootprintIOS/FootprintIOSKit/Sources/FootprintIOSKit.swift
  FootprintIOS/FootprintIOSKit/Tests/FootprintIOSKitTests.swift
  FootprintIOS/FootprintIOSUI/Sources/FootprintIOSUI.swift
  FootprintIOS/FootprintIOSUI/Tests/FootprintIOSUITests.swift
  Project.swift
  Tuist/Dependencies.swift
Labels: 🐿 소진, Set

#9 [Design] #7 - 정보 입력 UI 구현
  FootprintIOS/FootprintIOS/Resources/Assets/Colors.xcassets/BlueL.colorset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Colors.xcassets/GrayL.colorset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Colors.xcassets/YellowM.colorset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoButtonIcon.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoButtonIcon.imageset/Vector.svg
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoButtonIcon.imageset/Vector@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoButtonIcon.imageset/Vector@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoImage.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoImage.imageset/Group 1009.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoImage.imageset/Group 1009@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/bodyInfoImage.imageset/Group 1009@3x.png
  FootprintIOS/FootprintIOS/Sources/ViewController/Calendar/CalendarViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Info/InfoReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Info/InfoViewController.swift
Labels: ☁️ 영인, Design

#10 [Feat/#4] 뱃지 부분 UI 구현
  FootprintIOS/FootprintIOS/Resources/Assets/Colors.xcassets/White2.colorset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeBackground.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeBackground.imageset/badgeBackground.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeBackground.imageset/badgeBackground@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/badgeBackground.imageset/badgeBackground@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/emptyBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/emptyBadge.imageset/emptyBadge.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/emptyBadge.imageset/emptyBadge@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/emptyBadge.imageset/emptyBadge@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/proBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/proBadge.imageset/proBadge.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/proBadge.imageset/proBadge@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/proBadge.imageset/proBadge@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadge.imageset/representBadgeImage.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadge.imageset/representBadgeImage@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadge.imageset/representBadgeImage@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadgeBackground.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadgeBackground.imageset/representBadgeBackground.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadgeBackground.imageset/representBadgeBackground@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/representBadgeBackground.imageset/representBadgeBackground@3x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/startBadge.imageset/Contents.json
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/startBadge.imageset/startBadge.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/startBadge.imageset/startBadge@2x.png
  FootprintIOS/FootprintIOS/Resources/Assets/Images.xcassets/startBadge.imageset/startBadge@3x.png
  FootprintIOS/FootprintIOS/Sources/View/Badge/BadgeView.swift
  FootprintIOS/FootprintIOS/Sources/View/Badge/Cell/BadgeListCollectionViewCell.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Badge/BadgeModel.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Badge/BadgeViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
Labels: 🐿 소진, Style
