Repository UMC-1-Footprint/Footprint-iOS, pull requests merged in 2023-01, with the labels that each got.

#56 [Style/#55] 산책 기록 검색 UI
  FootprintIOS/FootprintIOS/Sources/Extension/String+Ext.swift
  FootprintIOS/FootprintIOS/Sources/View/Record/Cell/RecordCollectionViewCell.swift
  FootprintIOS/FootprintIOS/Sources/View/Record/Cell/RecordHeaderView.swift
  FootprintIOS/FootprintIOS/Sources/View/Reusable/HashTagStackView.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Record/RecordSearch/RecordSearchViewController.swift
Labels: 🐣 영모, Style

#58 [Feat/#57] 네트워크 서비스 레이어 구축
  FootprintIOS/FootprintIOS/Sources/AppDelegate.swift
  FootprintIOS/FootprintIOS/Sources/Config/KeyChainService.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/CreateWalkRequestDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/CreateWalkResponseDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/LoginRequestDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/LoginResponseDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/Domain/LoginProviderType.swift
  FootprintIOS/FootprintIOS/Sources/Model/Domain/Walk.swift
  FootprintIOS/FootprintIOS/Sources/Network/API/WalkAPI.swift
  FootprintIOS/FootprintIOS/Sources/Network/EndPoint/LoginEndPoint.swift
  FootprintIOS/FootprintIOS/Sources/Network/EndPoint/WalkEndPoint.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIError.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/APIManager.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/BaseArrayModel.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/EndPoint.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/NetworkRequest.swift
  FootprintIOS/FootprintIOS/Sources/Provider/APIProvider.swift
  FootprintIOS/FootprintIOS/Sources/Provider/Base/BaseProvider.swift
  FootprintIOS/FootprintIOS/Sources/Provider/EnviromentProvider.swift
  FootprintIOS/FootprintIOS/Sources/Provider/KeychainProvider.swift
  FootprintIOS/FootprintIOS/Sources/Provider/Provider.swift
  FootprintIOS/FootprintIOS/Sources/Service/Base/BaseService.swift
  FootprintIOS/FootprintIOS/Sources/Service/Base/LocalService.swift
  FootprintIOS/FootprintIOS/Sources/Service/Base/NetworkService.swift
  FootprintIOS/FootprintIOS/Sources/Service/KeychainService.swift
  FootprintIOS/FootprintIOS/Sources/Service/LoginService.swift
  FootprintIOS/FootprintIOS/Sources/Service/WalkService.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Login/LoginReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/MyPageViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/MyPage/Setting/SettingViewController.swift
Labels: 🐣 영모, Feature

#59 [Feat/#54] 알림창 로직 구현
  FootprintIOS/FootprintIOS/Sources/ViewController/Alert/AlertReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Alert/AlertViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Calendar/CalendarReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Calendar/CalendarViewController.swift
Labels: Feature

#69 [Feat/#62] 정보 입력, 목표 설정 서버 연결
  FootprintIOS/FootprintIOS/Sources/CompositionRoot.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/GoalRequestDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/GoalResponseDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/DTO/InfoRequestDTO.swift
  FootprintIOS/FootprintIOS/Sources/Model/Domain/GoalModel.swift
  FootprintIOS/FootprintIOS/Sources/Model/Domain/UserInfoRequestModel.swift
  FootprintIOS/FootprintIOS/Sources/Network/EndPoint/InfoEndPoint.swift
  FootprintIOS/FootprintIOS/Sources/Network/Foundation/DefaultResponse.swift
  FootprintIOS/FootprintIOS/Sources/Service/InfoService.swift
  FootprintIOS/FootprintIOS/Sources/View/UserInfo/Goal/GoalView.swift
  FootprintIOS/FootprintIOS/Sources/View/UserInfo/InfoTexts.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/Alert/AlertViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/DTO/GoalInfoDTO.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/DTO/UserInfoDTO.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalBottomSheet/GoalWalkBottomSheet/GoalWalkBottomSheetReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalBottomSheet/GoalWalkBottomSheet/GoalWalkBottomSheetViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalBottomSheet/WalkBottomSheet/WalkBottomSheetReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalBottomSheet/WalkBottomSheet/WalkBottomSheetViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalEdit/NextMonth/GoalEditNextMonthReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalEdit/NextMonth/GoalEditNextMonthViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalEdit/ThisMonth/GoalEditThisMonthReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalEdit/ThisMonth/GoalEditThisMonthViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Goal/GoalViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Info/InfoBottomSheet/BirthBottomSheetReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Info/InfoReactor.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Info/InfoViewController.swift
  FootprintIOS/FootprintIOS/Sources/ViewController/UserInfo/Info/Service/InfoService.swift
Labels: Feature
